import type { MobileClient } from '../api/client';import { acquireCallAudio,createNativeCallTransport,stopCallAudio,type NativeCallStream,type NativeCallTransport } from './native-media';import type { CallRecord,CallsView } from './contracts';
export interface NativeCallState{settings:CallsView['settings']|null;active:CallRecord|null;recent:CallRecord[];busy:boolean;loaded:boolean;connection:string;muted:boolean;error:string}
export class NativeCallController{
 private state:NativeCallState={settings:null,active:null,recent:[],busy:false,loaded:false,connection:'idle',muted:false,error:''};private listeners=new Set<()=>void>();private timer:any=null;private stream:NativeCallStream|null=null;private transport:NativeCallTransport|null=null;private localCallId:string|null=null;private sent=false;private received=false;private reconciling=false;private generation=0;
 constructor(private api:MobileClient,private rideId:string,private userId:string,private key:()=>string){}
 subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>this.listeners.delete(fn)};snapshot=()=>this.state;private patch(next:Partial<NativeCallState>){this.state={...this.state,...next};for(const fn of this.listeners)fn();}
 activate(){if(this.timer)return;void this.refresh();this.timer=setInterval(()=>void this.refresh(),2500)}pause(){if(this.timer)clearInterval(this.timer);this.timer=null}dispose(){this.pause();void this.end('client_closed');this.listeners.clear()}
 private release(){this.transport?.close();this.transport=null;stopCallAudio(this.stream);this.stream=null;this.localCallId=null;this.sent=false;this.received=false;this.patch({connection:'idle',muted:false});}
 async refresh(){const epoch=this.generation;try{const view=await this.api.calls();if(epoch!==this.generation)return;this.patch({settings:view.settings,active:view.active,recent:view.recent,loaded:true,error:''});if(this.localCallId&&view.active?.id!==this.localCallId)this.release();if(this.stream&&view.active?.id===this.localCallId&&view.active.status!=='ringing')await this.reconcile(view.active);}catch(e){if(epoch===this.generation)this.patch({loaded:true,error:e instanceof Error?e.message:'Calling is unavailable.'});}}
 private async acquire(){try{return await acquireCallAudio();}catch(e){throw new Error('Microphone access is unavailable. Allow microphone access and try again.');}}
 async start(){if(this.state.busy||this.state.active||!this.state.settings?.enabled)return;this.patch({busy:true,error:''});const epoch=++this.generation;let stream:NativeCallStream|null=null;try{stream=await this.acquire();if(epoch!==this.generation){stopCallAudio(stream);return;}const result=await this.api.startCall(this.rideId,this.key());this.stream=stream;this.localCallId=result.call.id;this.patch({active:result.call,connection:'ringing'});}catch(e){stopCallAudio(stream);this.patch({error:e instanceof Error?e.message:'Call could not start.'});}finally{this.patch({busy:false});void this.refresh();}}
 async answer(){const call=this.state.active;if(this.state.busy||!call||call.status!=='ringing'||call.callee.id!==this.userId)return;this.patch({busy:true,error:''});const epoch=++this.generation;let stream:NativeCallStream|null=null;try{stream=await this.acquire();const result=await this.api.callCommand(call.id,'accept',{expectedVersion:call.version},this.key());if(epoch!==this.generation){stopCallAudio(stream);return;}this.stream=stream;this.localCallId=result.call.id;this.patch({active:result.call,connection:'connecting'});await this.reconcile(result.call);}catch(e){stopCallAudio(stream);this.patch({error:e instanceof Error?e.message:'Call could not be answered.'});}finally{this.patch({busy:false});}}
 async decline(){const call=this.state.active;if(this.state.busy||!call||call.status!=='ringing'||call.callee.id!==this.userId)return;this.patch({busy:true});try{const r=await this.api.callCommand(call.id,'decline',{expectedVersion:call.version},this.key());this.patch({active:r.call});}catch(e){this.patch({error:e instanceof Error?e.message:'Call could not be declined.'});}finally{this.patch({busy:false});}}
 async end(reason:'hangup'|'media_failed'|'client_closed'='hangup'){const call=this.state.active,owned=call?.owned;this.generation++;this.release();if(!call||!owned)return;try{const r=await this.api.callCommand(call.id,'end',{reason},this.key());this.patch({active:r.call});}catch{this.patch({error:'Ending the call could not be confirmed. It will expire automatically.'});}}
 mute(){if(!this.stream)return;const next=!this.state.muted;this.transport?.mute(next);this.patch({muted:next});}
 private async reconcile(call:CallRecord){if(this.reconciling||!this.stream||!call.owned||call.status==='ringing')return;this.reconciling=true;try{const media=await this.api.callMedia(call.id);if(!this.transport)this.transport=createNativeCallTransport(media.configuration,this.stream,(connection)=>{this.patch({connection});if(['failed','closed'].includes(connection))void this.end('media_failed');});const caller=call.caller.id===this.userId;if(!this.sent){if(caller){const offer=await this.transport.describe('offer');await this.api.callCommand(call.id,'signal',offer,this.key());this.sent=true;}else if(media.remoteDescription?.type==='offer'){const answer=await this.transport.describe('answer',media.remoteDescription);await this.api.callCommand(call.id,'signal',answer,this.key());this.sent=true;this.received=true;}}
  if(caller&&media.remoteDescription?.type==='answer'&&!this.received){await this.transport.accept(media.remoteDescription);this.received=true;}await this.api.callPulse(call.id,this.transport.connected());}
 catch(e){this.patch({error:e instanceof Error?e.message:'Audio connection failed. Chat is still available.'});if(this.localCallId)void this.end('media_failed');}finally{this.reconciling=false;}}
}
