import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {openDatabase} from '../src/infrastructure/database.mjs';import {asAsyncDatabase} from '../src/infrastructure/async-database.mjs';import {createAudit} from '../src/infrastructure/audit.mjs';
import {createAdminMobileRepository} from '../src/modules/admin-mobile/repository.mjs';import {createAdminMobileService} from '../src/modules/admin-mobile/service.mjs';

test('Mobile Operations aggregates active device/build/push/API health and revokes one session idempotently',async t=>{
 const db=asAsyncDatabase(openDatabase(':memory:'));t.after(()=>db.close());const now=1_900_000_000_000,staff=randomUUID(),user=randomUUID(),session=randomUUID();
 for(const account of [{id:staff,email:'ops@example.test',name:'Ops',role:'admin'},{id:user,email:'rider@example.test',name:'Rider',role:'customer'}])await db.prepare('INSERT INTO users(id,email,name,role,password_hash,created_at) VALUES(?,?,?,?,?,?)').run(account.id,account.email,account.name,account.role,'fixture',now);
 await db.prepare('INSERT INTO device_sessions(id,user_id,name,access_hash,access_expires_at,created_at,refreshed_at,expires_at,idle_expires_at) VALUES(?,?,?,?,?,?,?,?,?)').run(session,user,'Android test','b'.repeat(64),now+600000,now,now,now+86400000,now+86400000);
 await db.prepare(`INSERT INTO mobile_device_health(session_id,user_id,platform,app_version,native_build,eas_build_id,build_profile,git_commit,os_version,location_permission,background_location_permission,notification_permission,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`)
  .run(session,user,'android','0.9.0',14,randomUUID(),'acceptance','a'.repeat(40),'15','granted','granted','granted',now,now);
 await db.prepare('INSERT INTO push_registrations(session_id,user_id,token) VALUES(?,?,?)').run(session,user,'ExponentPushToken[fixture-not-exposed]');
 await db.prepare('INSERT INTO mobile_api_samples(route_class,method,status_code,duration_ms,sample_weight,created_at) VALUES(?,?,?,?,?,?)').run('booking','GET',200,100,20,now);
 await db.prepare('INSERT INTO mobile_api_samples(route_class,method,status_code,duration_ms,sample_weight,created_at) VALUES(?,?,?,?,?,?)').run('booking','POST',500,250,1,now);
 const permissions=new Set(['mobile.read','mobile.manage']),repository=createAdminMobileRepository(db),service=createAdminMobileService({repository,requirePermission:async(_id,p)=>{if(!permissions.has(p))throw Object.assign(new Error('forbidden'),{code:'FORBIDDEN'});},unitOfWork:run=>db.transaction(run),audit:createAudit(db),clock:()=>now,releasePolicy:{ios:{minimumBuild:null,minimumVersion:null},android:{minimumBuild:12,minimumVersion:'0.9.0'}},sampleEvery:20});
 const result=await service.get(staff,{window:'24h',platform:'all'});assert.equal(result.summary.activeDevices,1);assert.equal(result.summary.reportingDevices,1);assert.equal(result.summary.pushRegistered,1);assert.equal(result.summary.latestAdoption,1);assert.equal(result.summary.unsupportedDevices,0);assert.equal(result.devices[0].platform,'android');assert.equal(result.devices[0].pushRegistered,true);assert.equal(result.api.estimatedRequests,21);assert.equal(result.api.serverErrors,1);assert.equal(JSON.stringify(result).includes('ExponentPushToken'),false);
 const key='mobile-revoke-command-key-123';assert.deepEqual(await service.revoke({userId:staff,sessionId:session,key}),{revoked:true,replayed:false});assert.deepEqual(await service.revoke({userId:staff,sessionId:session,key}),{revoked:true,replayed:true});
 assert.equal((await db.prepare('SELECT revoked_at FROM device_sessions WHERE id=?').get(session)).revoked_at,now);assert.equal((await db.prepare('SELECT count(*) AS n FROM push_registrations WHERE session_id=?').get(session)).n,0);assert.equal((await db.prepare("SELECT count(*) AS n FROM audit_events WHERE kind='admin.mobile.device_revoke'").get()).n,1);
});

test('Mobile Operations read-only staff cannot revoke devices',async()=>{
 const service=createAdminMobileService({repository:{summary:async()=>({}),devices:async()=>[],builds:async()=>[],pushJobs:async()=>[],tracking:async()=>({ride:{},food:{},background:0}),apiSamples:async()=>[]},requirePermission:async(_id,p)=>{if(p==='mobile.manage')throw Object.assign(new Error('forbidden'),{code:'FORBIDDEN'});},unitOfWork:run=>run(),audit:{record:async()=>{}},clock:()=>1,releasePolicy:{ios:{minimumBuild:null,minimumVersion:null},android:{minimumBuild:null,minimumVersion:null}},sampleEvery:20});
 const view=await service.get('viewer',{});assert.equal(view.canManage,false);await assert.rejects(service.revoke({userId:'viewer',sessionId:'11111111-1111-4111-8111-111111111111',key:'readonly-mobile-key-123'}),{code:'FORBIDDEN'});
});
