-- PostgreSQL 16+ baseline corresponding to SQLite schema 27.
-- JSON stays text at the repository boundary; indexed expressions cast to jsonb.
-- Epoch milliseconds and money require BIGINT; booleans retain the existing 0/1 contract.

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email CITEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('customer', 'driver', 'admin')),
  created_at BIGINT NOT NULL
);

CREATE TABLE drivers (
  user_id TEXT PRIMARY KEY REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  vehicle_model TEXT NOT NULL,
  vehicle_plate TEXT NOT NULL,
  reviewed_by TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  reviewed_at BIGINT
);

CREATE TABLE sessions (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  csrf_token TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE INDEX sessions_user ON sessions(user_id);

CREATE TABLE rides (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  driver_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  pickup_id TEXT NOT NULL,
  destination_id TEXT NOT NULL CHECK (destination_id <> pickup_id),
  suggested_fare_kobo BIGINT NOT NULL CHECK (suggested_fare_kobo > 0),
  status TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested', 'negotiating', 'agreed', 'cancelled')),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at BIGINT NOT NULL,
  matched_at BIGINT,
  updated_at BIGINT NOT NULL, request_expires_at BIGINT, closed_reason TEXT CHECK (closed_reason IS NULL OR closed_reason = 'request_expired'), driver_snapshot_json TEXT, vehicle_category TEXT NOT NULL DEFAULT 'standard'
  CHECK (vehicle_category IN ('standard', 'suv', 'van', 'truck', 'motorcycle')),
  CHECK (driver_id IS NULL OR driver_id <> customer_id),
  CHECK (status NOT IN ('negotiating', 'agreed') OR (driver_id IS NOT NULL AND matched_at IS NOT NULL))
);

CREATE UNIQUE INDEX one_open_customer_request ON rides(customer_id) WHERE status IN ('requested', 'negotiating');

CREATE UNIQUE INDEX one_driver_negotiation ON rides(driver_id) WHERE status = 'negotiating';

CREATE INDEX rides_available ON rides(status, created_at);

CREATE INDEX rides_driver ON rides(driver_id, created_at);

CREATE TABLE fare_events (
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  version BIGINT NOT NULL CHECK (version > 0),
  type TEXT NOT NULL CHECK (type IN ('propose', 'accept', 'cancel')),
  payload TEXT NOT NULL,
  PRIMARY KEY (ride_id, version)
);

CREATE TABLE audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  kind TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE rate_limits (
  key TEXT PRIMARY KEY,
  count BIGINT NOT NULL,
  reset_at BIGINT NOT NULL
);

CREATE TABLE chat_messages (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  sequence BIGINT NOT NULL CHECK (sequence > 0),
  sender_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  body TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 2000),
  created_at BIGINT NOT NULL,
  UNIQUE (ride_id, sequence)
);

CREATE TABLE chat_reads (
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  through_sequence BIGINT NOT NULL CHECK (through_sequence >= 0),
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (ride_id, user_id)
);

CREATE TABLE chat_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  message_id TEXT NOT NULL REFERENCES chat_messages(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE chat_reports (
  id TEXT PRIMARY KEY,
  message_id TEXT NOT NULL REFERENCES chat_messages(id) DEFERRABLE INITIALLY IMMEDIATE,
  reporter_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  reason TEXT NOT NULL CHECK (reason IN ('harassment', 'unsafe_request', 'spam', 'other')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewed')),
  created_at BIGINT NOT NULL,
  reviewed_by TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  reviewed_at BIGINT,
  UNIQUE (message_id, reporter_id)
);

CREATE INDEX chat_reports_queue ON chat_reports(status, created_at);

CREATE TABLE ride_trips (
  ride_id TEXT PRIMARY KEY REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  driver_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  status TEXT NOT NULL CHECK (status IN ('booked', 'on_way', 'arrived', 'in_progress', 'completed', 'cancelled')),
  fare_kobo BIGINT NOT NULL CHECK (fare_kobo > 0),
  booked_at BIGINT NOT NULL,
  departed_at BIGINT,
  arrived_at BIGINT,
  started_at BIGINT,
  completed_at BIGINT,
  pickup_pin TEXT,
  pin_failures BIGINT NOT NULL DEFAULT 0 CHECK (pin_failures BETWEEN 0 AND 5),
  pin_blocked_until BIGINT,
  CHECK (driver_id <> customer_id),
  CHECK ((status IN ('booked', 'on_way', 'arrived') AND pickup_pin IS NOT NULL AND length(pickup_pin) = 6 AND pickup_pin !~ '[^0-9]')
    OR (status IN ('in_progress', 'completed', 'cancelled') AND pickup_pin IS NULL)),
  CHECK (status NOT IN ('on_way', 'arrived', 'in_progress', 'completed') OR departed_at IS NOT NULL),
  CHECK (status NOT IN ('arrived', 'in_progress', 'completed') OR arrived_at IS NOT NULL),
  CHECK (status NOT IN ('in_progress', 'completed') OR started_at IS NOT NULL),
  CHECK (status <> 'completed' OR completed_at IS NOT NULL)
);

CREATE UNIQUE INDEX one_customer_trip ON ride_trips(customer_id) WHERE status NOT IN ('completed', 'cancelled');

CREATE UNIQUE INDEX one_driver_trip ON ride_trips(driver_id) WHERE status NOT IN ('completed', 'cancelled');

CREATE TABLE ride_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  type TEXT NOT NULL CHECK (type IN ('booked', 'on_way', 'arrived', 'in_progress', 'completed', 'cancelled')),
  reason TEXT CHECK (reason IN ('plans_changed', 'pickup_problem', 'other')),
  created_at BIGINT NOT NULL,
  CHECK ((type = 'cancelled' AND reason IS NOT NULL) OR (type <> 'cancelled' AND reason IS NULL))
);

CREATE INDEX ride_activity_ride ON ride_activity(ride_id, id);

CREATE TABLE voice_calls (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  caller_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  callee_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  status TEXT NOT NULL CHECK (status IN ('ringing', 'connecting', 'connected', 'ended', 'declined', 'missed', 'failed')),
  mode TEXT NOT NULL CHECK (mode IN ('local', 'relay')),
  version BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  answered_at BIGINT,
  connected_at BIGINT,
  ended_at BIGINT,
  ended_by TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  reason TEXT,
  caller_session TEXT NOT NULL,
  callee_session TEXT,
  caller_client TEXT NOT NULL,
  callee_client TEXT,
  caller_seen_at BIGINT NOT NULL,
  callee_seen_at BIGINT,
  caller_connected BIGINT NOT NULL DEFAULT 0 CHECK (caller_connected IN (0, 1)),
  callee_connected BIGINT NOT NULL DEFAULT 0 CHECK (callee_connected IN (0, 1)),
  offer_sdp TEXT,
  answer_sdp TEXT,
  CHECK (caller_id <> callee_id),
  CHECK (status NOT IN ('connecting', 'connected') OR (answered_at IS NOT NULL AND callee_session IS NOT NULL AND callee_client IS NOT NULL)),
  CHECK (status <> 'connected' OR connected_at IS NOT NULL),
  CHECK (status IN ('ringing', 'connecting', 'connected') OR (ended_at IS NOT NULL AND offer_sdp IS NULL AND answer_sdp IS NULL))
);

CREATE INDEX voice_calls_caller ON voice_calls(caller_id, created_at);

CREATE INDEX voice_calls_callee ON voice_calls(callee_id, created_at);

CREATE INDEX voice_calls_ride ON voice_calls(ride_id, created_at);

CREATE UNIQUE INDEX one_voice_call_per_ride ON voice_calls(ride_id) WHERE status IN ('ringing', 'connecting', 'connected');

CREATE TABLE voice_participants (
  user_id TEXT PRIMARY KEY REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  call_id TEXT NOT NULL REFERENCES voice_calls(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE voice_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  call_id TEXT NOT NULL REFERENCES voice_calls(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE location_quotes (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  route_json TEXT NOT NULL,
  ride_id TEXT UNIQUE REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX location_quotes_customer ON location_quotes(customer_id, created_at);

CREATE TABLE location_quote_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  quote_id TEXT NOT NULL REFERENCES location_quotes(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE location_shares (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  driver_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  active BIGINT NOT NULL CHECK (active IN (0, 1)),
  session_hash TEXT,
  client_hash TEXT,
  started_at BIGINT NOT NULL,
  seen_at BIGINT NOT NULL,
  stopped_at BIGINT,
  sequence BIGINT NOT NULL DEFAULT 0 CHECK (sequence >= 0),
  position_json TEXT,
  CHECK (active = 1 OR (position_json IS NULL AND session_hash IS NULL AND client_hash IS NULL AND stopped_at IS NOT NULL))
);

CREATE UNIQUE INDEX one_location_share_per_ride ON location_shares(ride_id) WHERE active = 1;

CREATE UNIQUE INDEX one_location_share_per_driver ON location_shares(driver_id) WHERE active = 1;

CREATE INDEX location_shares_ride ON location_shares(ride_id, started_at);

CREATE TABLE location_share_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  share_id TEXT NOT NULL REFERENCES location_shares(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE driver_availability (
  id TEXT PRIMARY KEY,
  driver_id TEXT NOT NULL REFERENCES drivers(user_id) DEFERRABLE INITIALLY IMMEDIATE,
  active BIGINT NOT NULL CHECK (active IN (0, 1)),
  mode TEXT NOT NULL CHECK (mode IN ('gps', 'sample')),
  area_id TEXT,
  position_json TEXT,
  session_hash TEXT,
  client_hash TEXT,
  sequence BIGINT NOT NULL CHECK (sequence > 0),
  started_at BIGINT NOT NULL,
  seen_at BIGINT NOT NULL,
  stopped_at BIGINT,
  reason TEXT CHECK (reason IN ('offline', 'expired', 'session_ended', 'approval_changed', 'claimed', 'snapshot_reset')), native_session_id TEXT,
  CHECK ((active = 1 AND session_hash IS NOT NULL AND client_hash IS NOT NULL AND stopped_at IS NULL AND reason IS NULL
    AND ((mode = 'gps' AND position_json IS NOT NULL AND area_id IS NULL) OR (mode = 'sample' AND area_id IS NOT NULL AND position_json IS NULL)))
    OR (active = 0 AND position_json IS NULL AND area_id IS NULL AND session_hash IS NULL AND client_hash IS NULL AND stopped_at IS NOT NULL AND reason IS NOT NULL))
);

CREATE UNIQUE INDEX one_online_driver ON driver_availability(driver_id) WHERE active = 1;

CREATE INDEX availability_driver ON driver_availability(driver_id, started_at);

CREATE TABLE availability_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  availability_id TEXT NOT NULL REFERENCES driver_availability(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id, key)
);

CREATE INDEX rides_request_expiry ON rides(request_expires_at) WHERE status = 'requested';

CREATE TABLE payments (
  ride_id TEXT PRIMARY KEY REFERENCES ride_trips(ride_id) DEFERRABLE INITIALLY IMMEDIATE,
  customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  driver_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  amount_kobo BIGINT NOT NULL CHECK (amount_kobo > 0 AND amount_kobo <= 9007199254740991),
  currency TEXT NOT NULL DEFAULT 'NGN' CHECK (currency = 'NGN'),
  mode TEXT NOT NULL DEFAULT 'simulation' CHECK (mode = 'simulation'),
  status TEXT NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'pending', 'failed', 'paid')),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  current_attempt_id TEXT,
  completed_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  paid_at BIGINT,
  CHECK (driver_id <> customer_id),
  CHECK ((status = 'unpaid' AND current_attempt_id IS NULL) OR (status <> 'unpaid' AND current_attempt_id IS NOT NULL)),
  CHECK ((status = 'paid' AND paid_at IS NOT NULL) OR (status <> 'paid' AND paid_at IS NULL))
);

CREATE INDEX payments_driver ON payments(driver_id, completed_at, ride_id);

CREATE INDEX payments_completed ON payments(completed_at, ride_id);

CREATE TABLE payment_attempts (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES payments(ride_id) DEFERRABLE INITIALLY IMMEDIATE,
  reference TEXT NOT NULL UNIQUE,
  amount_kobo BIGINT NOT NULL CHECK (amount_kobo > 0 AND amount_kobo <= 9007199254740991),
  currency TEXT NOT NULL CHECK (currency = 'NGN'),
  provider TEXT NOT NULL CHECK (provider = 'simulator'),
  status TEXT NOT NULL CHECK (status IN ('pending', 'failed', 'succeeded')),
  created_at BIGINT NOT NULL,
  resolved_at BIGINT,
  UNIQUE (ride_id, id),
  CHECK ((status = 'pending' AND resolved_at IS NULL) OR (status <> 'pending' AND resolved_at IS NOT NULL))
);

CREATE UNIQUE INDEX one_pending_payment_attempt ON payment_attempts(ride_id) WHERE status = 'pending';

CREATE INDEX payment_attempts_ride ON payment_attempts(ride_id, created_at, id);

CREATE TABLE payment_receipts (
  ride_id TEXT PRIMARY KEY REFERENCES payments(ride_id) DEFERRABLE INITIALLY IMMEDIATE,
  attempt_id TEXT NOT NULL UNIQUE,
  payload_json TEXT NOT NULL,
  FOREIGN KEY (ride_id, attempt_id) REFERENCES payment_attempts(ride_id, id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE payment_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  ride_id TEXT NOT NULL REFERENCES payments(ride_id) DEFERRABLE INITIALLY IMMEDIATE,
  attempt_id TEXT NOT NULL REFERENCES payment_attempts(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE driver_applications (
  driver_id TEXT PRIMARY KEY REFERENCES drivers(user_id) DEFERRABLE INITIALLY IMMEDIATE,
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','changes_requested','rejected','approved')),
  version BIGINT NOT NULL DEFAULT 0 CHECK(version >= 0),
  details_json TEXT,
  submitted_at BIGINT,
  updated_at BIGINT NOT NULL,
  reviewed_at BIGINT,
  reviewed_by TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  review_reason TEXT,
  verification_json TEXT
);

CREATE TABLE driver_documents (
  id TEXT PRIMARY KEY,
  driver_id TEXT NOT NULL REFERENCES driver_applications(driver_id) DEFERRABLE INITIALLY IMMEDIATE,
  kind TEXT NOT NULL CHECK(kind IN ('profile_photo','driving_licence','vehicle_registration','insurance','vehicle_photo')),
  name TEXT NOT NULL,
  mime_type TEXT NOT NULL CHECK(mime_type IN ('image/png','image/jpeg')),
  size_bytes BIGINT NOT NULL CHECK(size_bytes > 0 AND size_bytes <= 2097152),
  sha256 TEXT NOT NULL,
  expires_on TEXT,
  content BYTEA NOT NULL,
  created_at BIGINT NOT NULL,
  UNIQUE(driver_id,kind),
  CHECK(length(content)=size_bytes)
);

CREATE TABLE driver_document_reads (
  document_id TEXT NOT NULL REFERENCES driver_documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  reviewer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  read_at BIGINT NOT NULL,
  PRIMARY KEY(document_id,reviewer_id)
);

CREATE TABLE driver_application_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id TEXT NOT NULL REFERENCES driver_applications(driver_id) DEFERRABLE INITIALLY IMMEDIATE,
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  action TEXT NOT NULL,
  version BIGINT NOT NULL,
  payload_json TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE INDEX driver_events ON driver_application_events(driver_id,id);

CREATE TABLE driver_application_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  driver_id TEXT NOT NULL REFERENCES driver_applications(driver_id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY(actor_id,key)
);

CREATE TABLE trusted_contacts (
  id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  name TEXT,
  phone TEXT,
  active BIGINT NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
  version BIGINT NOT NULL DEFAULT 0 CHECK(version>=0),
  created_at BIGINT NOT NULL,
  removed_at BIGINT,
  CHECK((active=1 AND name IS NOT NULL AND phone IS NOT NULL AND removed_at IS NULL)
    OR (active=0 AND name IS NULL AND phone IS NULL AND removed_at IS NOT NULL))
);

CREATE UNIQUE INDEX contact_phone ON trusted_contacts(owner_id,phone) WHERE active=1;

CREATE TABLE safety_incidents (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  reporter_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  kind TEXT NOT NULL CHECK(kind IN ('need_help','possible_crash','unsafe_behaviour','other')),
  note TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','acknowledged','resolved')),
  version BIGINT NOT NULL DEFAULT 0 CHECK(version>=0),
  snapshot_json TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  acknowledged_by TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  resolved_at BIGINT
);

CREATE UNIQUE INDEX one_open_incident ON safety_incidents(ride_id,reporter_id) WHERE status<>'resolved';

CREATE INDEX safety_queue ON safety_incidents(status,created_at,id);

CREATE TABLE safety_incident_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id TEXT NOT NULL REFERENCES safety_incidents(id) DEFERRABLE INITIALLY IMMEDIATE,
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  action TEXT NOT NULL,
  note TEXT NOT NULL,
  version BIGINT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE safety_notifications (
  id TEXT PRIMARY KEY,
  incident_id TEXT NOT NULL REFERENCES safety_incidents(id) DEFERRABLE INITIALLY IMMEDIATE,
  contact_id TEXT NOT NULL REFERENCES trusted_contacts(id) DEFERRABLE INITIALLY IMMEDIATE,
  recipient_name TEXT NOT NULL,
  recipient_phone TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'simulation' CHECK(mode='simulation'),
  status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sent','delivered','failed','cancelled')),
  version BIGINT NOT NULL DEFAULT 0 CHECK(version>=0),
  attempts BIGINT NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 3),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE(incident_id,contact_id)
);

CREATE TABLE safety_notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id TEXT NOT NULL REFERENCES safety_notifications(id) DEFERRABLE INITIALLY IMMEDIATE,
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  status TEXT NOT NULL,
  attempt BIGINT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE trip_share_links (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  token_hash TEXT UNIQUE,
  session_hash TEXT,
  active BIGINT NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
  version BIGINT NOT NULL DEFAULT 0 CHECK(version>=0),
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  ended_at BIGINT,
  reason TEXT CHECK(reason IN ('revoked','replaced','expired','session_ended','trip_ended','snapshot_reset')),
  CHECK((active=1 AND token_hash IS NOT NULL AND session_hash IS NOT NULL AND ended_at IS NULL)
    OR (active=0 AND token_hash IS NULL AND session_hash IS NULL AND ended_at IS NOT NULL))
);

CREATE UNIQUE INDEX one_trip_link ON trip_share_links(owner_id,ride_id) WHERE active=1;

CREATE TABLE safety_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  PRIMARY KEY(actor_id,key)
);

CREATE TABLE account_capabilities (
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  capability TEXT NOT NULL CHECK (capability IN ('customer', 'driver')),
  created_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, capability)
);

CREATE TABLE account_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE device_sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  name TEXT NOT NULL,
  access_hash TEXT NOT NULL UNIQUE,
  access_expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  refreshed_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  idle_expires_at BIGINT NOT NULL,
  revoked_at BIGINT
);

CREATE INDEX device_sessions_owner ON device_sessions(user_id, expires_at);

CREATE TABLE device_refresh_tokens (
  token_hash TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES device_sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  used_at BIGINT
);

CREATE INDEX device_refresh_family ON device_refresh_tokens(session_id);

CREATE TABLE driver_vehicle_selections (
  driver_id TEXT PRIMARY KEY REFERENCES driver_applications(driver_id) DEFERRABLE INITIALLY IMMEDIATE,
  vehicle_json TEXT NOT NULL CHECK(((vehicle_json)::jsonb IS NOT NULL))
);

CREATE INDEX admin_accounts_created ON users(created_at,id);

CREATE INDEX admin_rides_created ON rides(created_at,id);

CREATE INDEX admin_customer_trips ON rides(customer_id,created_at,id);

CREATE TABLE account_password_settings (
  user_id TEXT PRIMARY KEY REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  enabled BIGINT NOT NULL CHECK (enabled IN (0, 1))
);

CREATE TABLE account_identities (
  provider TEXT NOT NULL CHECK (provider = 'google'),
  subject TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (provider, subject),
  UNIQUE (user_id, provider)
);

CREATE TABLE google_auth_attempts (
  state_hash TEXT PRIMARY KEY,
  binding_hash TEXT NOT NULL,
  nonce TEXT NOT NULL,
  verifier TEXT,
  channel TEXT NOT NULL CHECK (channel IN ('web', 'native')),
  intent TEXT NOT NULL CHECK (intent IN ('login', 'link')),
  origin TEXT,
  actor_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  session_hash TEXT,
  expires_at BIGINT NOT NULL
);

CREATE INDEX google_auth_expiry ON google_auth_attempts(expires_at);

CREATE TABLE account_email_verifications (
  user_id TEXT PRIMARY KEY REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  email TEXT NOT NULL,
  verified_at BIGINT NOT NULL
);

CREATE TABLE account_email_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  purpose TEXT NOT NULL CHECK (purpose IN ('verify', 'reset')),
  email TEXT NOT NULL,
  credential_hash TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  UNIQUE(user_id, purpose)
);

CREATE INDEX account_email_token_expiry ON account_email_tokens(expires_at);

CREATE TABLE account_email_jobs (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  purpose TEXT NOT NULL CHECK (purpose IN ('verify', 'reset', 'changed')),
  email TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  next_attempt_at BIGINT NOT NULL,
  attempts BIGINT NOT NULL DEFAULT 0,
  lease_id TEXT,
  lease_until BIGINT NOT NULL DEFAULT 0,
  UNIQUE(user_id, purpose)
);

CREATE INDEX account_email_job_schedule ON account_email_jobs(next_attempt_at, lease_until);

CREATE TABLE delivery_orders (
  ride_id TEXT PRIMARY KEY REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  details_json TEXT NOT NULL,
  dropoff_pin TEXT,
  pin_failures BIGINT NOT NULL DEFAULT 0 CHECK (pin_failures >= 0),
  pin_blocked_until BIGINT,
  verified_at BIGINT
);

CREATE TABLE "idempotency" (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  error_code TEXT CHECK (error_code IS NULL OR error_code IN ('INVALID_PICKUP_PIN', 'INVALID_DELIVERY_PIN')),
  PRIMARY KEY (actor_id, key)
);

CREATE TABLE account_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  kind TEXT NOT NULL CHECK(kind IN ('request','claim','propose','accept','confirm','depart','arrive','start','complete','cancel','expired','message')),
  mode TEXT NOT NULL CHECK(mode IN ('customer','work')),
  event_key TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  read_at BIGINT,
  UNIQUE(user_id,event_key)
);

CREATE INDEX notifications_owner ON account_notifications(user_id,id DESC);

CREATE TABLE push_registrations (
  session_id TEXT PRIMARY KEY REFERENCES device_sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  token TEXT NOT NULL UNIQUE
);

CREATE TABLE push_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id BIGINT NOT NULL REFERENCES account_notifications(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  session_id TEXT NOT NULL REFERENCES device_sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  token TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','ticket','done','dead')),
  attempts BIGINT NOT NULL DEFAULT 0,
  next_at BIGINT NOT NULL,
  ticket TEXT,
  UNIQUE(notification_id,session_id)
);

CREATE INDEX push_due ON push_jobs(status,next_at);

CREATE TABLE vehicle_photo_checks (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  command_key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  expected_json TEXT NOT NULL,
  result_json TEXT,
  state TEXT NOT NULL CHECK (state IN ('pending','complete','unavailable','trip_ended')),
  model TEXT NOT NULL,
  consent_version TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  completed_at BIGINT,
  expires_at BIGINT NOT NULL,
  UNIQUE(owner_id,command_key)
);

CREATE INDEX vehicle_checks_ride ON vehicle_photo_checks(owner_id,ride_id,created_at);

CREATE INDEX vehicle_checks_expiry ON vehicle_photo_checks(expires_at);

CREATE INDEX vehicle_checks_rate ON vehicle_photo_checks(created_at,state);

CREATE TABLE eats_stores (
  id TEXT PRIMARY KEY, status TEXT NOT NULL CHECK(status IN ('pending','approved','suspended')),
  version BIGINT NOT NULL DEFAULT 0, is_open BIGINT NOT NULL DEFAULT 0 CHECK(is_open IN (0,1)),
  details_json TEXT NOT NULL, review_note TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
);

CREATE TABLE eats_memberships (
  user_id TEXT PRIMARY KEY REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  role TEXT NOT NULL CHECK(role = 'owner')
);

CREATE INDEX eats_store_members ON eats_memberships(store_id);

CREATE TABLE eats_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  reviewer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, decision TEXT NOT NULL, reason TEXT NOT NULL,
  reference TEXT NOT NULL, created_at BIGINT NOT NULL
);

CREATE TABLE eats_menu (
  id TEXT PRIMARY KEY, store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  available BIGINT NOT NULL CHECK(available IN (0,1)), details_json TEXT NOT NULL
);

CREATE INDEX eats_store_menu ON eats_menu(store_id,id);

CREATE TABLE eats_quotes (
  id TEXT PRIMARY KEY, customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  store_version BIGINT NOT NULL, snapshot_json TEXT NOT NULL, expires_at BIGINT NOT NULL, order_id TEXT
);

CREATE INDEX eats_quote_expiry ON eats_quotes(expires_at);

CREATE TABLE eats_orders (
  id TEXT PRIMARY KEY, store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE, customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  courier_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, status TEXT NOT NULL CHECK(status IN ('placed','accepted','preparing','ready','assigned','picked_up','arrived','delivered','cancelled','rejected')),
  version BIGINT NOT NULL DEFAULT 0, snapshot_json TEXT NOT NULL, courier_json TEXT,
  pickup_pin TEXT, delivery_pin TEXT, pin_failures BIGINT NOT NULL DEFAULT 0, pin_blocked_until BIGINT,
  events_json TEXT NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
);

CREATE UNIQUE INDEX eats_one_courier_job ON eats_orders(courier_id) WHERE status IN ('assigned','picked_up','arrived');

CREATE INDEX eats_customer_orders ON eats_orders(customer_id,created_at DESC,id DESC);

CREATE INDEX eats_store_orders ON eats_orders(store_id,created_at DESC,id DESC);

CREATE INDEX eats_courier_orders ON eats_orders(courier_id,created_at DESC,id DESC);

CREATE INDEX eats_ready_orders ON eats_orders(status,created_at,id);

CREATE TABLE eats_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, key TEXT NOT NULL, fingerprint TEXT NOT NULL,
  result_json TEXT NOT NULL, created_at BIGINT NOT NULL, PRIMARY KEY(actor_id,key)
);

CREATE TABLE eats_photos (
  id TEXT PRIMARY KEY,
  store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  base64 TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE INDEX eats_photos_store ON eats_photos(store_id);

CREATE TABLE eats_checkouts (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  quote_ids_json TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE INDEX eats_checkouts_customer ON eats_checkouts(customer_id);

CREATE TABLE eats_collection_points (
  order_id TEXT PRIMARY KEY REFERENCES eats_orders(id) DEFERRABLE INITIALLY IMMEDIATE,
  location TEXT NOT NULL
);

CREATE TABLE guest_ride_passengers (
  ride_id TEXT PRIMARY KEY REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  snapshot_json TEXT NOT NULL CHECK(((snapshot_json)::jsonb IS NOT NULL) AND ((snapshot_json)::jsonb #>> '{kind}')='guest')
);

CREATE TABLE guest_ride_links (
  _insert_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  token_hash TEXT UNIQUE,
  session_binding TEXT,
  active BIGINT NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
  version BIGINT NOT NULL DEFAULT 0 CHECK(version>=0),
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL CHECK(expires_at>created_at AND expires_at<=created_at+86400000),
  ended_at BIGINT,
  reason TEXT CHECK(reason IN ('revoked','replaced','expired','session_ended','trip_ended','snapshot_reset')),
  CHECK((active=1 AND token_hash IS NOT NULL AND session_binding IS NOT NULL AND ended_at IS NULL AND reason IS NULL)
    OR (active=0 AND token_hash IS NULL AND session_binding IS NULL AND ended_at IS NOT NULL AND reason IS NOT NULL))
);

CREATE UNIQUE INDEX one_guest_ride_link ON guest_ride_links(ride_id) WHERE active=1;

CREATE INDEX guest_ride_link_history ON guest_ride_links(ride_id,created_at);

CREATE TABLE guest_ride_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  link_id TEXT NOT NULL REFERENCES guest_ride_links(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY(actor_id,key)
);

CREATE TABLE eats_store_dispatch_points (
  store_id TEXT PRIMARY KEY REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  lat DOUBLE PRECISION NOT NULL CHECK(lat BETWEEN -90 AND 90),
  lng DOUBLE PRECISION NOT NULL CHECK(lng BETWEEN -180 AND 180)
);

CREATE TABLE eats_order_dispatch_points (
  order_id TEXT PRIMARY KEY REFERENCES eats_orders(id) DEFERRABLE INITIALLY IMMEDIATE,
  lat DOUBLE PRECISION NOT NULL CHECK(lat BETWEEN -90 AND 90),
  lng DOUBLE PRECISION NOT NULL CHECK(lng BETWEEN -180 AND 180)
);

CREATE INDEX eats_store_area ON eats_stores(((details_json)::jsonb #>> '{areaId}'), status, created_at DESC);

CREATE INDEX eats_ready_area ON eats_orders(status, ((snapshot_json)::jsonb #>> '{restaurant,areaId}'), created_at);

CREATE TABLE ride_driver_ratings (
  ride_id TEXT PRIMARY KEY REFERENCES rides(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  customer_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  driver_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  stars BIGINT NOT NULL CHECK(stars BETWEEN 1 AND 5),
  created_at BIGINT NOT NULL
);

CREATE INDEX ride_driver_ratings_driver ON ride_driver_ratings(driver_id, created_at DESC);

CREATE TABLE eats_menu_photos (
  item_id TEXT PRIMARY KEY REFERENCES eats_menu(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  store_id TEXT NOT NULL REFERENCES eats_stores(id) DEFERRABLE INITIALLY IMMEDIATE,
  content BYTEA NOT NULL,
  size_bytes BIGINT NOT NULL CHECK(size_bytes > 0 AND size_bytes <= 1048576),
  version BIGINT NOT NULL CHECK(version > 0)
);

CREATE INDEX eats_menu_photos_store ON eats_menu_photos(store_id);

CREATE TABLE safety_monitor_sessions (
  owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  binding TEXT NOT NULL, enabled BIGINT NOT NULL CHECK(enabled IN (0,1)),
  preferences_json TEXT NOT NULL, version BIGINT NOT NULL DEFAULT 0, expires_at BIGINT NOT NULL,
  PRIMARY KEY(owner_id,ride_id)
);

CREATE TABLE safety_auto_alerts (
  id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  kind TEXT NOT NULL CHECK(kind IN ('impact','distress','manual')), signal_json TEXT NOT NULL,
  snapshot_json TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('countdown','queued','cancelled','expired','finished')),
  created_at BIGINT NOT NULL, due_at BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX safety_one_countdown ON safety_auto_alerts(owner_id,ride_id) WHERE status IN ('countdown','queued');

CREATE TABLE safety_delivery_jobs (
  id TEXT PRIMARY KEY, alert_id TEXT NOT NULL REFERENCES safety_auto_alerts(id) DEFERRABLE INITIALLY IMMEDIATE, contact_id TEXT REFERENCES trusted_contacts(id) DEFERRABLE INITIALLY IMMEDIATE,
  recipient_json TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('queued','sending','accepted','failed','cancelled','unavailable')),
  attempts BIGINT NOT NULL DEFAULT 0, next_at BIGINT NOT NULL, lease_until BIGINT NOT NULL DEFAULT 0,
  provider_reference TEXT, UNIQUE(alert_id,contact_id)
);

CREATE INDEX safety_delivery_due ON safety_delivery_jobs(status,next_at);

CREATE TABLE safety_risk_zones (
  id TEXT PRIMARY KEY, reporter_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, label TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL, lng DOUBLE PRECISION NOT NULL, radius_m BIGINT NOT NULL, note TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected','withdrawn')),
  created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0,
  review_note TEXT, reviewer_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE safety_monitor_commands (
  owner_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE, key TEXT NOT NULL, fingerprint TEXT NOT NULL,
  PRIMARY KEY(owner_id,key)
);

CREATE TABLE dispatch_offers (
  id TEXT PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  driver_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  availability_id TEXT NOT NULL REFERENCES driver_availability(id) DEFERRABLE INITIALLY IMMEDIATE,
  status TEXT NOT NULL CHECK (status IN ('pending','accepted','declined','expired','revoked')),
  mode TEXT NOT NULL CHECK (mode IN ('sequential','batch')),
  policy_version TEXT NOT NULL,
  eta_source TEXT NOT NULL CHECK (eta_source IN ('road','distance_fallback','sample')),
  pickup_eta_seconds DOUBLE PRECISION,
  estimated_at BIGINT,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL CHECK (expires_at > created_at),
  closed_at BIGINT,
  CHECK ((eta_source='road' AND pickup_eta_seconds >= 0 AND estimated_at IS NOT NULL)
    OR (eta_source!='road' AND pickup_eta_seconds IS NULL AND estimated_at IS NULL)),
  CHECK ((status='pending' AND closed_at IS NULL) OR (status!='pending' AND closed_at IS NOT NULL)),
  UNIQUE (ride_id,driver_id)
);

CREATE UNIQUE INDEX dispatch_one_ride ON dispatch_offers(ride_id) WHERE status='pending';

CREATE UNIQUE INDEX dispatch_one_driver ON dispatch_offers(driver_id) WHERE status='pending';

CREATE INDEX dispatch_pending_expiry ON dispatch_offers(expires_at) WHERE status='pending';

CREATE TABLE dispatch_commands (
  actor_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY IMMEDIATE,
  key TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  offer_id TEXT NOT NULL REFERENCES dispatch_offers(id) DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY (actor_id,key)
);

CREATE TABLE dispatch_journeys (
  ride_id TEXT PRIMARY KEY REFERENCES rides(id) DEFERRABLE INITIALLY IMMEDIATE,
  mode TEXT NOT NULL CHECK (mode IN ('legacy','sequential','batch')),
  location_mode TEXT NOT NULL CHECK (location_mode IN ('sample','gps')),
  created_at BIGINT NOT NULL,
  matched_at BIGINT,
  booked_at BIGINT,
  departed_at BIGINT,
  arrived_at BIGINT,
  completed_at BIGINT,
  closed_at BIGINT,
  outcome TEXT CHECK (outcome IN ('cancelled','expired'))
);

CREATE INDEX dispatch_journey_cohort ON dispatch_journeys(created_at,mode,location_mode);

ALTER TABLE payments ADD CONSTRAINT payments_current_attempt_fk FOREIGN KEY(ride_id,current_attempt_id) REFERENCES payment_attempts(ride_id,id) DEFERRABLE INITIALLY IMMEDIATE;
