-- Preserve existing vendor images as legacy content, without claiming a new review.
ALTER TABLE eats_photos ADD COLUMN purpose TEXT NOT NULL DEFAULT 'dish' CHECK(purpose IN ('dish','logo','cover','menu_reference'));
ALTER TABLE eats_photos ADD COLUMN status TEXT NOT NULL DEFAULT 'legacy-approved' CHECK(status IN ('pending','approved','rejected','legacy-approved','private'));
ALTER TABLE eats_photos ADD COLUMN version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0);
ALTER TABLE eats_photos ADD COLUMN review_note TEXT;
ALTER TABLE eats_photos ADD COLUMN size_bytes INTEGER NOT NULL DEFAULT 0 CHECK(size_bytes >= 0);
UPDATE eats_photos SET size_bytes=octet_length(decode(base64,'base64'));
CREATE INDEX eats_photo_review_queue ON eats_photos(status,created_at,id);
CREATE TABLE eats_store_assets (
  store_id TEXT NOT NULL REFERENCES eats_stores(id),
  purpose TEXT NOT NULL CHECK(purpose IN ('logo','cover','menu_reference')),
  photo_id TEXT NOT NULL UNIQUE REFERENCES eats_photos(id),
  PRIMARY KEY(store_id,purpose)
);
CREATE TABLE eats_photo_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_id TEXT NOT NULL,
  store_id TEXT NOT NULL REFERENCES eats_stores(id),
  reviewer_id TEXT NOT NULL REFERENCES users(id),
  decision TEXT NOT NULL CHECK(decision IN ('approved','rejected')),
  reason TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

-- Canonicalize legacy item-only photos before retiring duplicate blob storage.
DO $$
DECLARE legacy RECORD; canonical_id TEXT;
BEGIN
  FOR legacy IN SELECT p.item_id,p.store_id,p.content,p.version,m.details_json FROM eats_menu_photos p JOIN eats_menu m ON m.id=p.item_id LOOP
    canonical_id := (legacy.details_json::jsonb)->>'photoId';
    IF canonical_id IS NULL OR NOT EXISTS(SELECT 1 FROM eats_photos WHERE id=canonical_id AND store_id=legacy.store_id) THEN
      canonical_id := gen_random_uuid()::text;
      INSERT INTO eats_photos(id,store_id,base64,created_at,size_bytes,version)
        VALUES(canonical_id,legacy.store_id,replace(encode(legacy.content,'base64'),E'\n',''),0,octet_length(legacy.content),legacy.version);
      UPDATE eats_menu SET details_json=jsonb_set(legacy.details_json::jsonb,'{photoId}',to_jsonb(canonical_id))::text WHERE id=legacy.item_id;
    END IF;
    DELETE FROM eats_menu_photos WHERE item_id=legacy.item_id;
  END LOOP;
END;
$$;
